# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: 'BuildAndPushDockerImage'
    jobs:
      - job: 'dockerBuildAndPush'
        pool: 
          vmImage: 'ubuntu-latest'
        timeoutInMinutes: 0
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'vivekgupta434-dockerhub-serviceconnection'
            repository: 'vivekgupta434/pythonTerraformApp'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest
        - task: SendEmail@2
          condition: always()
          inputs:
            To: 'vg52531@gmail.com'
            From: 'vgupta.cse.2016@nist.edu'
            Subject: 'Azure-pipelines Python-terraform-app Status'
            Body: |
              Hello,
              
              The Azure DevOps pipeline for repository $(Build.Repository.Name) has completed.
              
                Build Number: $(Build.BuildNumber)  
               ️ Status: $(Build.Status)  
                Branch: $(Build.SourceBranchName)  
                Build URL: $(Build.BuildUri)
              
              Thanks,  
              DevOps Team
            BodyAsHtml: false
            AddAttachment: false
            SmtpServer: 'smtp.gmail.com'
            SmtpPort: '465'
            SmtpUsername: 'vgupta.cse.2016@nist.edu'
            SmtpPassword: '$(gmail-pass)'
