# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: 'BuildAndPushDockerImage'
    jobs:
      - job: 'dockerBuildAndPush'
        pool: 
          vmImage: 'ubuntu-latest'
        timeoutInMinutes: 0
        steps:
        - task: Docker@2
          inputs:
            command: 'build'
            Dockerfile: '**/Dockerfile'
